# AMOSTRAGEM

In [1]:
import pandas as pd
import random
import numpy as np

from sklearn.model_selection import StratifiedShuffleSplit

In [2]:
df = pd.read_csv('Bases/census.csv')
df.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

## Amostragem Aleatória Simples

In [3]:
df_amostra_simples = df.sample(n = 100)

In [4]:
df_amostra_simples.shape

(100, 15)

In [5]:
df_amostra_simples.head()

age          workclass  final-weight      education  education-num  \
16989   50            Private        104501        Masters             14   
604     35   Self-emp-not-inc        194404     Assoc-acdm             12   
9715    24            Private        585203      Bachelors             13   
21701   26            Private        391349      Bachelors             13   
29099   22            Private        300871   Some-college             10   

            marital-status        occupation    relationship    race      sex  \
16989   Married-civ-spouse    Prof-specialty         Husband   White     Male   
604          Never-married   Farming-fishing   Not-in-family   White     Male   
9715    Married-civ-spouse   Exec-managerial            Wife   White   Female   
21701   Married-civ-spouse      Adm-clerical            Wife   White   Female   
29099   Married-civ-spouse      Tech-support         Husband   White     Male   

       capital-gain  capital-loos  hour-per-week  native-country  income  
16989             0             0             40   United-States    >50K  
604               0             0             40   United-States   <=50K  
9715           7688             0             45   United-States    >50K  
21701             0             0             40   United-States    >50K  
29099             0             0             40   United-States   <=50K

## Amostragem Sistemática

In [6]:
df.shape

(32561, 15)

In [7]:
# selecao de 100 amostras
len(df) // 100 #será selecionado um valor entre 1 e 325 e depois "pular" de 325 em 325 posicoes

325

In [8]:
random.seed(10)
random.randint(0, 325)

292

In [9]:
np.arange(68, len(df), step = 325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [10]:
def amostragem_sistematica(dataset, amostras):
    intervalo = len(dataset) // amostras
    random.seed(1)
    inicio = random.randint(0, intervalo)
    indices = np.arange(inicio, len(dataset), step = intervalo)
    amostra_sistematica = df.iloc[indices]
    return amostra_sistematica

In [11]:
df_amostra_sistematica = amostragem_sistematica(df, 100)
df_amostra_sistematica.shape

(100, 15)

In [12]:
df_amostra_sistematica.head()

age      workclass  final-weight      education  education-num  \
68     49   Self-emp-inc        191681   Some-college             10   
393    34      State-gov         98101      Bachelors             13   
718    22        Private        214399   Some-college             10   
1043   44        Private        167005      Bachelors             13   
1368   52        Private        152234        HS-grad              9   

           marital-status        occupation relationship                 race  \
68     Married-civ-spouse   Exec-managerial      Husband                White   
393    Married-civ-spouse   Exec-managerial      Husband                White   
718         Never-married             Sales    Own-child                White   
1043   Married-civ-spouse   Exec-managerial      Husband                White   
1368   Married-civ-spouse   Exec-managerial      Husband   Asian-Pac-Islander   

          sex  capital-gain  capital-loos  hour-per-week  native-country  \
68       Male             0             0             50   United-States   
393      Male          7688             0             45               ?   
718    Female             0             0             15   United-States   
1043     Male          7688             0             60   United-States   
1368     Male         99999             0             40           Japan   

      income  
68      >50K  
393     >50K  
718    <=50K  
1043    >50K  
1368    >50K

## Amostragem por Grupos

In [13]:
len(df) / 10 # 10 grupos

3256.1

In [14]:
grupos = []
id_grupo = 0
contagem = 0

for _ in df.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo += 1

In [15]:
np.unique(grupos)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.unique(grupos, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [17]:
np.shape(grupos), df.shape

((32561,), (32561, 15))

In [18]:
df['grupos'] = grupos

In [19]:
random.randint(0, 9)

9

In [20]:
df_agrupamento = df[df['grupos'] == 9]
df_agrupamento

age      workclass  final-weight      education  education-num  \
29313   45        Private        285060      Bachelors             13   
29314   28      State-gov        189765   Some-college             10   
29315   23        Private        130905      Bachelors             13   
29316   50        Private        146325        HS-grad              9   
29317   33        Private        102821           12th              8   
...    ...            ...           ...            ...            ...   
32556   27        Private        257302     Assoc-acdm             12   
32557   40        Private        154374        HS-grad              9   
32558   58        Private        151910        HS-grad              9   
32559   22        Private        201490        HS-grad              9   
32560   52   Self-emp-inc        287927        HS-grad              9   

            marital-status          occupation relationship    race      sex  \
29313   Married-civ-spouse     Exec-managerial      Husband   White     Male   
29314            Separated        Adm-clerical    Unmarried   White   Female   
29315        Never-married               Sales    Own-child   White   Female   
29316   Married-civ-spouse        Craft-repair      Husband   White     Male   
29317   Married-civ-spouse     Protective-serv      Husband   White     Male   
...                    ...                 ...          ...     ...      ...   
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

       capital-gain  capital-loos  hour-per-week  native-country  income  \
29313             0             0             50   United-States    >50K   
29314             0             0             50   United-States   <=50K   
29315             0             0             40   United-States   <=50K   
29316             0             0             44   United-States    >50K   
29317             0             0             40   United-States   <=50K   
...             ...           ...            ...             ...     ...   
32556             0             0             38   United-States   <=50K   
32557             0             0             40   United-States    >50K   
32558             0             0             40   United-States   <=50K   
32559             0             0             20   United-States   <=50K   
32560         15024             0             40   United-States    >50K   

       grupos  
29313       9  
29314       9  
29315       9  
29316       9  
29317       9  
...       ...  
32556       9  
32557       9  
32558       9  
32559       9  
32560       9  

[3248 rows x 16 columns]

## Amostragem Estratificada

In [21]:
df['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [22]:
7841 / len(df), 24720 / len(df)

(0.2408095574460244, 0.7591904425539756)

In [23]:
split = StratifiedShuffleSplit(test_size = 0.1)

for x, y in split.split(df, df['income']):
    df_x = df.iloc[x]
    df_y = df.iloc[y]
    
    

In [24]:
df_x.shape, df_y.shape

((29304, 16), (3257, 16))

## Amostragem de Reservatório

In [26]:
stream = []

for i in range(len(df)):
    stream.append(i)

In [29]:
#print(stream)

In [37]:
def amostragem_reservatorio(dataset, amostras):
    stream = []

    for i in range(len(df)):
        stream.append(i)
        
    i = 0
    tamanho = len(dataset)
    
    reservatorio = [0] * amostras
    for i in range(amostras):
        reservatorio[i] = stream[i]
        
    while i < tamanho:
        j = random.randrange(i + 1)
        if j < amostras:
            reservatorio[j] = stream[i]
        i += 1
        
    return dataset.iloc[reservatorio]

In [38]:
df_amostragem_reservatorio = amostragem_reservatorio(df, 100)
df_amostragem_reservatorio.head()

age     workclass  final-weight      education  education-num  \
12792   57       Private        231232        7th-8th              4   
14480   61   Federal-gov         60641   Some-college             10   
18649   66     Local-gov        261062        Masters             14   
17410   43       Private        247880        HS-grad              9   
18469   17       Private        104232           10th              6   

            marital-status       occupation    relationship    race      sex  \
12792   Married-civ-spouse     Craft-repair         Husband   White     Male   
14480   Married-civ-spouse     Adm-clerical            Wife   White   Female   
18649              Widowed   Prof-specialty   Not-in-family   White   Female   
17410        Never-married     Craft-repair   Not-in-family   White     Male   
18469        Never-married    Other-service       Own-child   White     Male   

       capital-gain  capital-loos  hour-per-week  native-country  income  \
12792             0             0             40   United-States   <=50K   
14480             0             0             30   United-States   <=50K   
18649             0             0             40   United-States   <=50K   
17410             0             0             40   United-States   <=50K   
18469             0             0             10   United-States   <=50K   

       grupos  
12792       3  
14480       4  
18649       5  
17410       5  
18469       5

In [39]:
df_amostragem_reservatorio.shape

(100, 16)